on:
  push:
    paths:
      - 'package-set.dhall'
      - 'example/**'
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aviate-labs/setup-dfx@v0.2.3
        with:
          dfx-version: 0.8.6
          vessel-version: 0.6.2
      - run: |
          cd example
          moc $(vessel sources) --check src/main.mo
