on:
  push:
    paths:
      - 'package-set.dhall'
jobs:
  package-set:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aviate-labs/setup-dfx@v0.2.3
        with:
          dfx-version: 0.11.2
          vessel-version: 0.6.3
      - run: vessel verify --version 0.7.0
